CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(512) NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`coverImageUrl` varchar(1024),
	`inlineImages` json,
	`category` varchar(128),
	`tags` json,
	`status` enum('draft','review','published') NOT NULL DEFAULT 'draft',
	`aiGenerated` boolean NOT NULL DEFAULT false,
	`trendingTopic` varchar(512),
	`linkedinPost` text,
	`mediumIntro` text,
	`redditPost` text,
	`metaDescription` varchar(160),
	`readTimeMinutes` int,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
